// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOZyU6jX6g18rN-rqUoi0LeRDY00uVGXU',
    appId: '1:1048919459319:web:e25ed11a5d7c36ee485af2',
    messagingSenderId: '1048919459319',
    projectId: 'yukaapp-94d89',
    authDomain: 'yukaapp-94d89.firebaseapp.com',
    storageBucket: 'yukaapp-94d89.firebasestorage.app',
    measurementId: 'G-SGZYJKFR8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFgK13-wNtMfcAzat2teMICqm4qqUUdmQ',
    appId: '1:1048919459319:android:ed1ae82308d6cf89485af2',
    messagingSenderId: '1048919459319',
    projectId: 'yukaapp-94d89',
    storageBucket: 'yukaapp-94d89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2H2TdS_s1RaTuNlbDOSL-xMf84tCdqb0',
    appId: '1:1048919459319:ios:d8429a13be28f855485af2',
    messagingSenderId: '1048919459319',
    projectId: 'yukaapp-94d89',
    storageBucket: 'yukaapp-94d89.firebasestorage.app',
    iosBundleId: 'com.example.yukaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2H2TdS_s1RaTuNlbDOSL-xMf84tCdqb0',
    appId: '1:1048919459319:ios:d8429a13be28f855485af2',
    messagingSenderId: '1048919459319',
    projectId: 'yukaapp-94d89',
    storageBucket: 'yukaapp-94d89.firebasestorage.app',
    iosBundleId: 'com.example.yukaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOZyU6jX6g18rN-rqUoi0LeRDY00uVGXU',
    appId: '1:1048919459319:web:adfb4b4e2f0ca374485af2',
    messagingSenderId: '1048919459319',
    projectId: 'yukaapp-94d89',
    authDomain: 'yukaapp-94d89.firebaseapp.com',
    storageBucket: 'yukaapp-94d89.firebasestorage.app',
    measurementId: 'G-MVB3E30CFF',
  );

}